# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/2K-paper',
                'doc_host': 'https://nd-crane.github.io',
                'git_url': 'https://github.com/nd-crane/2K-paper',
                'lib_path': '2K_paper'},
  'syms': {'2K_paper.core': {'2K_paper.core.foo': ('core.html#foo', '2K_paper/core.py')}}}
