# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/trusted_ke',
                'doc_host': 'https://nd-crane.github.io',
                'git_url': 'https://github.com/nd-crane/trusted_ke',
                'lib_path': 'trusted_ke'},
  'syms': {'trusted_ke.core': {'trusted_ke.core.foo': ('core.html#foo', 'trusted_ke/core.py')}}}
