# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/2K-paper',
                'doc_host': 'https://nd-crane.github.io',
                'git_url': 'https://github.com/nd-crane/2K-paper',
                'lib_path': 'paper2k'},
  'syms': { 'paper2k.core': { 'paper2k.core._fetch_query': ('core.html#_fetch_query', 'paper2k/core.py'),
                              'paper2k.core._search_wikidata_properties_async': ( 'core.html#_search_wikidata_properties_async',
                                                                                  'paper2k/core.py'),
                              'paper2k.core.search_wikidata_properties': ('core.html#search_wikidata_properties', 'paper2k/core.py')}}}
