# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/trusted-ke',
                'doc_host': 'https://nd-crane.github.io',
                'git_url': 'https://github.com/nd-crane/trusted-ke',
                'lib_path': './trusted-ke'},
  'syms': { 'trusted-ke.core': { 'trusted-ke.core._fetch_query': ('core.html#_fetch_query', 'trusted-ke/core.py'),
                                 'trusted-ke.core._search_wikidata_properties_async': ( 'core.html#_search_wikidata_properties_async',
                                                                                        'trusted-ke/core.py'),
                                 'trusted-ke.core.excel_to_csv_to_df': ('core.html#excel_to_csv_to_df', 'trusted-ke/core.py'),
                                 'trusted-ke.core.search_wikidata_properties': ( 'core.html#search_wikidata_properties',
                                                                                 'trusted-ke/core.py')}}}
